
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname msk-as1001-r12
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
clock timezone +11 11 0
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
!
!
!
ip domain name msk.local
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
username admin privilege 15 secret 5 $1$FMqo$CQLFgb3GL.aQpuC0MjSe70
!
redundancy
!
!
ip ssh version 2
! 
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback0
 no shutdown
 description routers-managment
 ip address 10.0.100.12 255.255.255.255
 ip ospf 1 area 10
!
interface Ethernet0/0
 no shutdown
 description trunk-to-sw4
 no ip address
!
interface Ethernet0/0.101
 no shutdown
 description managment
 encapsulation dot1Q 101
 ip address 10.0.101.12 255.255.255.0
!
interface Ethernet0/0.1000
 no shutdown
 description wrk-1000
 encapsulation dot1Q 1000
 ip address 192.168.100.12 255.255.255.0
 ip policy route-map PBR_SERVICES
!
interface Ethernet0/0.1001
 no shutdown
 description wrk-1001
 encapsulation dot1Q 1001
 ip address 192.168.101.12 255.255.255.0
 ip policy route-map PBR_SERVICES
!
interface Ethernet0/1
 no shutdown
 no ip address
 shutdown
!
interface Ethernet0/2
 no shutdown
 description to-r14
 ip address 172.16.0.5 255.255.255.252
 ip ospf 1 area 10
!
interface Ethernet0/3
 no shutdown
 description to-r15
 ip address 172.16.0.9 255.255.255.252
 ip ospf 1 area 10
!
interface Ethernet1/0
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/1
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/2
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/3
 no shutdown
 no ip address
 shutdown
!
router ospf 1
 router-id 10.0.100.12
 area 10 stub
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
!
route-map PBR_SERVICES permit 10
 match ip address 100
 set ip next-hop 172.16.0.6
!
route-map PBR_SERVICES permit 20
 match ip address 101
 set ip next-hop 172.16.0.9 172.16.0.10
!
!
access-list 100 permit tcp any any eq www
access-list 100 permit tcp any any eq 443
access-list 101 permit tcp any any eq ftp-data
access-list 101 permit tcp any any eq ftp
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login local
 transport input ssh
!
!
end
