
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname msk-as1001-r15
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
clock timezone +11 11 0
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
!
!
!
ip domain name msk.local
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
username admin privilege 15 secret 5 $1$priP$nILpvwT.zv/H5XXtMt8RH/
!
redundancy
!
!
ip ssh version 2
! 
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback0
 no shutdown
 description routers_managment
 ip address 10.0.100.15 255.255.255.255
 ip ospf 1 area 0
!
interface Ethernet0/0
 no shutdown
 description to-r13
 ip address 172.16.0.18 255.255.255.252
 ip ospf 1 area 10
!
interface Ethernet0/1
 no shutdown
 description to-r12
 ip address 172.16.0.10 255.255.255.252
 ip ospf 1 area 10
!
interface Ethernet0/2
 no shutdown
 description to-as301-r21
 ip address 172.16.0.29 255.255.255.252
!
interface Ethernet0/3
 no shutdown
 description to-r20
 ip address 172.16.0.22 255.255.255.252
 ip ospf 1 area 102
!
interface Ethernet1/0
 no shutdown
 description description to-r14
 ip address 172.16.0.94 255.255.255.252
 ip ospf 1 area 0
!
interface Ethernet1/1
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/2
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/3
 no shutdown
 no ip address
 shutdown
!
router ospf 1
 router-id 10.0.100.15
 area 10 stub
 area 102 filter-list prefix BLOCK-A101 in
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
!
ip prefix-list BLOCK-A101 seq 15 deny 10.0.100.19/32
ip prefix-list BLOCK-A101 seq 20 permit 0.0.0.0/0 le 32
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login local
 transport input ssh
!
!
end
