
!
! Last configuration change at 14:36:58 +11 Wed Jul 22 2026
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname spb-as2042-r16
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
clock timezone +11 11 0
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
!
!
!
ip domain name spb.local
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
username admin privilege 15 secret 5 $1$kJBh$UFxBOHI2DGqkPKca.kp8Y0
!
redundancy
!
!
ip ssh version 2
! 
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback0
 no shutdown
 description routers_managment
 ip address 10.0.100.16 255.255.255.255
!
interface Ethernet0/0
 no shutdown
 description to-sw10
 no ip address
!
interface Ethernet0/0.101
 no shutdown
 description managment
 encapsulation dot1Q 101
 ip address 10.0.102.16 255.255.255.0
!
interface Ethernet0/0.1000
 no shutdown
 description wrk-1000
 encapsulation dot1Q 1000
 ip address 192.168.102.16 255.255.255.0
!
interface Ethernet0/0.1001
 no shutdown
 description wrk-1001
 encapsulation dot1Q 1001
 ip address 192.168.103.16 255.255.255.0
!
interface Ethernet0/1
 no shutdown
 description to-r18
 ip address 172.16.0.73 255.255.255.252
!
interface Ethernet0/2
 no shutdown
 no ip address
 shutdown
!
interface Ethernet0/3
 no shutdown
 description to-r32
 ip address 172.16.0.77 255.255.255.252
!
!
router eigrp SPB
 !
 address-family ipv4 unicast autonomous-system 2042
  !
  af-interface Ethernet0/1
   summary-address 192.168.102.0 255.255.254.0
  exit-af-interface
  !
  af-interface Ethernet0/3
   summary-address 0.0.0.0 0.0.0.0
  exit-af-interface
  !
  topology base
   summary-metric 0.0.0.0/0 distance 250
  exit-af-topology
  network 10.0.100.16 0.0.0.0
  network 172.16.0.72 0.0.0.3
  network 172.16.0.76 0.0.0.3
  network 192.168.102.0 0.0.1.255
  eigrp router-id 10.0.100.16
 exit-address-family
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login local
 transport input ssh
!
!
end
