
!
! Last configuration change at 19:21:19 +11 Wed Oct 7 2026
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname msk-as1001-r14
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
clock timezone +11 11 0
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
!
!
!
ip domain name msk.local
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
username admin privilege 15 secret 5 $1$Tbmb$QXuPK2wwvYc.6jM3HYr6k/
!
redundancy
!
!
ip ssh version 2
! 
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback0
 no shutdown
 description routers_managment
 ip address 10.0.100.14 255.255.255.255
 ip ospf 1 area 0
!
interface Tunnel1
 no shutdown
 ip address 172.31.1.1 255.255.255.0
 no ip redirects
 ip mtu 1400
 ip nhrp map multicast dynamic
 ip nhrp network-id 1
 ip nhrp redirect
 ip tcp adjust-mss 1360
 tunnel source Loopback0
 tunnel mode gre multipoint
 tunnel key 1
!
interface Tunnel12
 no shutdown
 ip address 172.31.0.1 255.255.255.252
 ip mtu 1400
 ip tcp adjust-mss 1360
 tunnel source Loopback0
 tunnel destination 10.0.100.18
 tunnel key 12
!
interface Ethernet0/0
 no shutdown
 description to-r12
 ip address 172.16.0.6 255.255.255.252
 ip nat inside
 ip virtual-reassembly in
 ip ospf 1 area 10
!
interface Ethernet0/1
 no shutdown
 description to-r13
 ip address 172.16.0.14 255.255.255.252
 ip nat inside
 ip virtual-reassembly in
 ip ospf 1 area 10
!
interface Ethernet0/2
 no shutdown
 description to-as101-r22
 ip address 172.16.0.25 255.255.255.252
 ip nat outside
 ip virtual-reassembly in
!
interface Ethernet0/3
 no shutdown
 description to-r19
 ip address 172.16.0.2 255.255.255.252
 ip nat inside
 ip virtual-reassembly in
 ip ospf 1 area 101
!
interface Ethernet1/0
 no shutdown
 description description to-r15
 ip address 172.16.0.93 255.255.255.252
 ip nat inside
 ip virtual-reassembly in
 ip ospf 1 area 0
!
interface Ethernet1/1
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/2
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/3
 no shutdown
 no ip address
 shutdown
!
router ospf 1
 router-id 10.0.100.14
 area 10 stub
 area 101 stub no-summary
 redistribute bgp 1001 subnets
!
router bgp 1001
 bgp router-id 10.0.100.14
 bgp log-neighbor-changes
 neighbor 10.0.100.15 remote-as 1001
 neighbor 10.0.100.15 update-source Loopback0
 neighbor 172.16.0.26 remote-as 101
 !
 address-family ipv4
  network 10.0.100.14 mask 255.255.255.255
  aggregate-address 192.168.100.0 255.255.254.0 summary-only
  redistribute ospf 1 match internal external 1 external 2
  neighbor 10.0.100.15 activate
  neighbor 10.0.100.15 next-hop-self
  neighbor 172.16.0.26 activate
  neighbor 172.16.0.26 filter-list 10 out
 exit-address-family
!
ip forward-protocol nd
!
ip as-path access-list 10 permit ^$
!
no ip http server
no ip http secure-server
ip nat inside source list NAT-MSK interface Ethernet0/2 overload
ip nat inside source static tcp 10.0.100.19 22 interface Ethernet0/2 22
!
ip access-list standard NAT-MSK
 permit 10.0.100.0 0.0.0.255
 permit 10.0.101.0 0.0.0.255
 permit 192.168.100.0 0.0.0.255
 permit 192.168.101.0 0.0.0.255
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login local
 transport input ssh
!
ntp server 10.0.100.12
ntp server 10.0.100.13
!
end
