
!
! Last configuration change at 20:15:02 +11 Wed Oct 7 2026
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname chok-as103-r28
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
clock timezone +11 11 0
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
!
!
!
ip domain name chok.local
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
username admin privilege 15 secret 5 $1$wJ0x$tmjr/RlUf8OVPGKQcg2T50
!
redundancy
!
!
ip ssh version 2
! 
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback0
 no shutdown
 description routers_managment
 ip address 10.0.100.28 255.255.255.255
!
interface Tunnel1
 no shutdown
 ip address 172.31.1.27 255.255.255.0
 no ip redirects
 ip mtu 1400
 ip nhrp network-id 1
 ip nhrp nhs 172.31.1.1 nbma 10.0.100.14 multicast
 ip nhrp shortcut
 ip tcp adjust-mss 1360
 tunnel source Loopback0
 tunnel mode gre multipoint
 tunnel key 1
!
interface Ethernet0/0
 no shutdown
 description to-as520-r26
 ip address 172.16.0.90 255.255.255.252
 ip nat outside
 ip virtual-reassembly in
!
interface Ethernet0/1
 no shutdown
 description to-as520-r25
 ip address 172.16.0.86 255.255.255.252
 ip nat outside
 ip virtual-reassembly in
!
interface Ethernet0/2
 no shutdown
 description to-sw29
 no ip address
 ip nat outside
 ip virtual-reassembly in
!
interface Ethernet0/2.101
 no shutdown
 description managment
 encapsulation dot1Q 101
 ip address 10.0.103.28 255.255.255.0
!
interface Ethernet0/2.1000
 no shutdown
 description wrk-1000
 encapsulation dot1Q 1000
 ip address 192.168.104.28 255.255.255.0
!
interface Ethernet0/2.1001
 no shutdown
 description wrk-1001
 encapsulation dot1Q 1001
 ip address 192.168.105.28 255.255.255.0
!
interface Ethernet0/3
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/0
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/1
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/2
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/3
 no shutdown
 no ip address
 shutdown
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
ip nat inside source list NAT-CHOK interface Ethernet0/1 overload
ip route 0.0.0.0 0.0.0.0 172.16.0.85
!
ip access-list standard NAT-CHOK
 permit 10.0.102.0 0.0.0.255
 permit 192.168.104.0 0.0.0.255
 permit 192.168.105.0 0.0.0.255
 permit 10.0.103.0 0.0.0.255
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login local
 transport input ssh
!
!
end
