
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname msk-as1001-r13
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
clock timezone +11 11 0
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!


!
!
!
!
ip domain name msk.local
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
username admin privilege 15 secret 5 $1$cmbR$4TlN9Fah3SbZfbMulHNP40
!
redundancy
!
!
ip ssh version 2
! 
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback0
 no shutdown
 description routers-managment
 ip address 10.0.100.13 255.255.255.255
!
interface Ethernet0/0
 no shutdown
 description trunk-to-sw5
 no ip address
!
interface Ethernet0/0.101
 no shutdown
 description managment
 encapsulation dot1Q 101
 ip address 10.0.101.13 255.255.255.0
!
interface Ethernet0/0.1000
 no shutdown
 description wrk-1000
 encapsulation dot1Q 1000
 ip address 192.168.100.13 255.255.255.0
!
interface Ethernet0/0.1001
 no shutdown
 description wrk-1001
 encapsulation dot1Q 1001
 ip address 192.168.101.13 255.255.255.0
!
interface Ethernet0/1
 no shutdown
 no ip address
 shutdown
!
interface Ethernet0/2
 no shutdown
 description to-r15
 ip address 172.16.0.17 255.255.255.252
!
interface Ethernet0/3
 no shutdown
 description to-r14
 ip address 172.16.0.13 255.255.255.252
!
interface Ethernet1/0
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/1
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/2
 no shutdown
 no ip address
 shutdown
!
interface Ethernet1/3
 no shutdown
 no ip address
 shutdown
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
!
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login local
 transport input ssh
!
!
end
